replicaCount: 1

image:
  repository: <your-repo>/webshop
  tag: latest
  pullPolicy: IfNotPresent

env:
  kinesisStreamName: ""
  logfireUrl: "" 
  logfireToken: "" 

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}
