replicaCount: 1

image:
  repository: <your-repo>/webshop
  tag: latest
  pullPolicy: IfNotPresent

env:
  kinesisStreamName: ""
  logfireUrl: "" 

secrets:  
  logfireToken: "" 

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}

serviceAccount:
  create: false
  name: ""
  automount: true
  annotations: {}
