replicaCount: 1

image:
  repository: <your-repo>/webshop
  tag: latest
  pullPolicy: Always

env:
  kinesisStreamName: ""
  logfireUrl: "" 

secrets:  
  logfireToken: "" 

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}

serviceAccount:
  create: false
  name: ""
  automount: true
  annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    - hosts:
        - "example.com"
      secretName: "example-tls-secret"
  hosts:
    - host: "example.com"
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: "" 
