# Basic checks for linting, syntax errors, formatting, ...
name: App CI/CD

on: 
  push:
    branches:
      - main

jobs:
  ruff-format:
      runs-on: ubuntu-latest
      steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - run: ruff format

  pylint:
    needs: [ruff-format]
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/webshop/requirements.txt
    
    - name: check-code
      run: |
        pylint $(git ls-files '*.py') --fail-under=8.5
  
  docker-image:
    needs: [pylint, ruff-format]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    
    - name: log-in-docker-hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # For later:
    # - name: login-aws-ecr
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ${{ vars.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_REGION_ECR }}.amazonaws.com
    #     username: ${{ vars.AWS_ACCESS_KEY_ID }}
    #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./src/webshop/
        push: true
        tags: ${{ vars.DOCKERHUB_USER }}webshop/app:latest
        