name: Deploy Dev Environment

on:
  workflow_dispatch:

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    
    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: authenticate-to-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.TF_AWS_REGION }}
        aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}

    - name: download backend.config
      run: |
        aws s3 cp s3://cep-7-static/terraform/backend/backend.config ./terraform/environments/dev/backend.config
        
    - name: init-and-validate
      id: tf_apply
      working-directory: terraform/environments/dev/
      run: |
        terraform init -backend-config=backend.config
        terraform validate
        terraform apply -auto-approve
    
    