name: (3) Destroy Dev 

on:
  workflow_dispatch:

jobs:
  destroy-dev:
    runs-on: ubuntu-latest 

    steps:
    - name: checkout 
      uses: actions/checkout@v4

    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: package-and-upload-scripts
      run: |
        zip lambda_emr_trigger.zip scripts/lambda/emr_step_raw_bronze.py

    - name: authenticate-to-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.TF_AWS_REGION }}

    - name: acquire-backend.config
      run: |
        aws s3 cp s3://cep-7-static/terraform/backend/backend.config ./terraform/environments/dev/backend.config
    
    - name: destroy-dev
      working-directory: terraform/environments/dev/
      run: |
        terraform init -backend-config=backend.config
        terraform destroy -auto-approve \
          -var="image_repo=${{ vars.ECR_REPO }}" \
          -var="eks_svc_acc_name=eks-aws-access"
        