name: Destroy Backend

on:
  workflow_dispatch:

jobs:
  destroy-backend:
    runs-on: ubuntu-latest 

    steps:
    - name: checkout 
      uses: actions/checkout@v4

    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: authenticate-to-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.TF_AWS_REGION }}

    - name: acquire-state
      run: |
        aws s3 mv s3://cep-7-static/terraform/backend/terraform.tfstate ./terraform/backend/terraform.tfstate
    
    - name: destroy-backend
      working-directory: terraform/backend/
      run: |
        terraform init
        terraform state pull
        terraform destroy -auto-approve
        