# test TerraForm with
# - terraform validate
# - tflint
# - checkov

name: TerraForm Backend

on:
  workflow_dispatch:

jobs:
  provide-backend:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: authenticate-to-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.TF_AWS_REGION }}
        aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
        
    - name: init-and-validate
      working-directory: terraform/backend/
      run: |
        terraform init
        terraform validate
        terraform apply -auto-approve
        terraform output > backend.config
    
    - name: list files
      run: ls -R
    
    - name: upload state
      uses: actions/upload-artifact@v4
      with:
        name: terraform-tfstate
        path: ./terraform.tfstate

    - name: upload config
      uses: actions/upload-artifact@v4 
      with:
        name: backend-config
        path: ./backend.config
