name: TerraForm Backend Destroy

on:
  workflow_dispatch:

jobs:
  destroy-backend:
    runs-on: ubuntu-latest 

    steps:
    - name: checkout 
      uses: actions/checkout@v4

    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: destroy-backend
      working-directory: "terraform/backend"
      run: |
        terraform destroy -auto-approve
