apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  KINESIS_STREAM_NAME: {{ .Values.env.kinesisStreamName }}
  LOGFIRE_URL: {{ .Values.env.logfireUrl }}
  ELASTICSEARCH_URL: {{ .Values.env.opensearchUrl }}
